---
title: "Ressourcen für OGD im Kanton Zürich "
---

# OGD Ressourcen

-   OGD Folien: https://docs.google.com/presentation/d/1FKm8-ybTiIfU6l3AImm42H0DuWWxbjhmM58TXJfNRjk/edit#slide=id.g164f80efa60_0_14
-   OGD Leitlinien: https://www.zh.ch/de/politik-staat/opendata/leitlinien.html#-932898780
-   OGD Handbook Publikationsleitlinien: https://github.com/openZH/ogd-handbook/blob/main/publikationsleitlinien.md

# GitHub

-   GitHub Organisation openZH: https://github.com/openZH
-   GitHub Organisation statistikZH: https://github.com/statistikZH/

# OGD Community

- Viva Engage Einstiegs Community "Data" im neuen Intranet & Tool: https://engage.cloud.microsoft/main/groups/eyJfdHlwZSI6Ikdyb3VwIiwiaWQiOiI0NjQ2ODQ0MDA2NSJ9

- Teams Data Community of Practice: https://teams.microsoft.com/l/team/19%3Ag5aGGUm_wpjMXL1muNuKioEcl0YI041XzI0r1s87K481%40thread.tacv2/conversations?groupId=0ffbe0c2-40db-49df-8043-60dac2139834&tenantId=a020d0ae-094a-4d44-b66c-ac3fe8e90c58

- R Austausch: Der R-Austausch richtet sich an R Nutzer*innen in der Zürcher Kantonsverwaltung. Er dient als Plattform für den Wissensaustausch und der Vernetzung rund um die offene Statistiksoftware R. (https://statistikzh.github.io/rstats_ktzh/)

- Open Data Beer: opendatabeer.ch

- adminR: adminR meetup: https://www.meetup.com/adminr/

# OGD Beispiele

Was kann man mit OGD machen damit machen?

-   Leerwohnungsziffer nach Gemeinden: https://www.zh.ch/de/planen-bauen/raumplanung/immobilienmarkt/leerwohnungen.html#-291192554
-   Gewaltopfer Häusliche Gewalt: https://www.zh.ch/de/sicherheit-justiz/delikte-praevention/kriminalstatistik/gewaltopfer.html
-   Decarb-Monitoring (Daten sind semi OGD, da sie in einem offenen GitHub-repo liegen): https://www.zh.ch/de/umwelt-tiere/klima/langfristige-klimastrategie/monitoring.html
-   Kurzzeitmessung NIS: https://www.zh.ch/de/umwelt-tiere/luft-strahlung/mobilfunk.html#1645502451
- und die Seite https://www.zh.ch/de/umwelt-tiere/klima/klimakarte-daten.html#1132125233 könnte auch noch als Beispiel genutzt werden.
    - App: https://openzh.shinyapps.io/Lokalklima/
    - Die dargestellten Messdaten stehen auch als OGD zur Verfügung: https://opendata.swiss/de/dataset/lufttemperatur-und-luftfeuchte-lora-sensor-messwerte
- statistikZH/decarb_monitoring: Repository für den Bezug der Daten fürs Dekarbonisierungsmonitoring des Kantons Zürich (github.com): https://github.com/statistikZH/decarb_monitoring

- awelZH/nis_meas_school: Repository for NIS measurements on school grounds within the Canton of Zurich (github.com): https://github.com/awelZH/nis_meas_school