---
title: "Modul 6"
subtitle: "{{< var md-06.titel >}}"
editor: source
params:
    modul: 6
execute: 
  echo: false
  warning: false
bibliography: referenzen.bib
editor_options: 
  chunk_output_type: console
---

## Lernziele

```{r}
#| label: setup

library(epoxy)
```

```{r}
#| label: learning-objectives

lernziele <- readr::read_csv(here::here("data/tbl-01-rstatszh-k009-lernziele.csv")) |> 
  dplyr::filter(modul == params$modul) |>
  dplyr::pull(lernziele)

```

```{epoxy}
{1:length(lernziele)}. {lernziele[1:length(lernziele)]}
```

## {{< fa display >}} Folien

[Zeige Folien im Vollbildmodus an](../folien/md-06-daten-typen.html) | [Download slides as PDF](https://github.com/rstatszh-k009/website/raw/main/folien/md-06-daten-typen.pdf)

```{=html}
<iframe class="slide-deck" src="../folien/md-06-daten-typen.html" height="420" width="747" style="border: 1px solid #123233;"></iframe>
```

## {{< fa book >}} Lesematerial

- Lies aus dem Buch "What they forgot to teach you about R": [Sektion 3 - Project-oriented workflow"](https://rstats.wtf/projects) 
- Lies aus dem Buch "What they forgot to teach you about R": [Sektion 4 - Practice safe paths"](https://rstats.wtf/practice-safe-paths) 
- Lies: [R for Data Science - Section 9 - Layers](https://r4ds.hadley.nz/layers)

## {{< fa code >}} Übungsaufgaben

- [Zusatzaufgabe 1](../zusatzaufgaben/md-06/za-06-01-abschlussprojekt.qmd): Abschlussprojekt 